### ISSUE TITLE
question on setup self-hosted models (vLLM)

### ISSUE THREAD

**Issue by JingtongSu** [microsoft/deep-language-networks#44]
Hi, thanks for your great work!

I'm new to DLN, and I'm trying to use LLaMa2 models to replace the GPT series reported in the paper as the forward/backward models. I followed the setup procedure in the README file, namely to export the huggingface path to the LLaMa2 tokenizer, and used the [script](https://github.com/microsoft/deep-language-networks/blob/4292c2263a8da59c2a181dcaecc22633ece8c121/projects/vi_dln/scripts/two_layers_e2e/navigate_vllm.sh) for two-layer joint end-to-end training. Unfortunately, I got `openai.error.APIConnectionError: Error communicating with OpenAI` and the training procedure was broken.

I investigated the code a bit and found the "generate" [function](https://github.com/microsoft/deep-language-networks/blob/main/dln/operator.py#L292) of the VLLM class involves querying the `openai.Completion.acreate` function/API. Is that the expected behavior when I switch to self-hosted models? I suspect there should be a dependency on [vLLM](https://github.com/vllm-project/vllm), but I did not find one.

Thanks in advance if you could help me with this :)!

**Comment by JingtongSu** [comment]
The script in this repo requires manually initiating a vLLM with the openai-compatible server beforehand! I will close this issue.

**Comment by matheper** [comment]
Hi @JingtongSu,

You are right. DLN does not manage the serving of models. The instructions describe how to connect to an LLM that is already hosted using vLLM. I apologize for any confusion; we are updating the documentation to better reflect this.

You can follow this [instruction on how to set up an OpenAI compatible server using vLLM](https://docs.vllm.ai/en/latest/getting_started/quickstart.html#openai-compatible-server)

Once your vLLM server is operational, you can refer to it as detailed in the DLN readme.

**Comment by JingtongSu** [comment]
Hi @matheper, thanks for your quick reply! I have already figured that out and made my own DLN running. Thanks for taking the time of making the code public again :)
